imagePullPolicy: "Always"                         # image pull policy

## statefulset:
replicas: 1                                     # The number of replicas
dockerImage: "ghost"                            
dockerTag: "4.9.4-alpine"                      

# Labels
component: "frontend"                       

## Resources
# requests
mem: "200Mi"                                # amout of memory requested
cpu: "200m"                                 # cpu requested
# limits
mem: "200Mi"                                # max memory 
cpu: "200m"                                 # max cpu

# Readiness
initialDelaySeconds: 30                       # time to wait before readiness starts
timeoutSeconds: 5                             # readiness timeout

# Liveness
initialDelaySeconds: 30                       # time to wait before liveness starts
timeoutSeconds: 5                             # liveliness timeout
periodSeconds: 10                             # liveliness period

# Ports 
name: web                                     # name of the port
protocol: TCP                                 # protocol to use
port: 2368                                    # port number
targetPort: 2368                              # target port for the service
