apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ghost
  labels:
    app: ghost
    component: {{ .Values.component }}
spec:
  serviceName: ghost
  replicas: {{ .Values.replicas }}

  selector:
    matchLabels:
      app: ghost
      component: frontend

  template:
    metadata:
      labels:
        app: ghost
        component: {{ .Values.component }}

    spec:
      containers:
      - name: ghost
        image: {{ .Values.dockerImage }}:{{ .Values.dockerTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}

        readinessProbe:
          httpGet:
            path: /
            port: 2368
          initialDelaySeconds: {{ .Values.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.timeoutSeconds }}

        livenessProbe:
          httpGet:
            path: /
            port: 2368
          initialDelaySeconds: {{ .Values.initialDelaySeconds }}
          periodSeconds: {{ .Values.periodSeconds }}
          timeoutSeconds: {{ .Values.timeoutSeconds }}

        resources:
          requests:
            cpu: {{ .Values.cpu }}
            memory: {{ .Values.mem }}
          limits:
            cpu: {{ .Values.cpu }}
            memory: {{ .Values.mem }}

        ports:
        - name: web
          protocol: TCP
          containerPort: 2368

        volumeMounts:
        - mountPath: /var/lib/ghost/content
          name: content

  volumeClaimTemplates:
  - metadata:
      name: content
      namespace: dev
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 500Mi
