apiVersion: v1
kind: Service
metadata:
  name: ghost
  labels:
    app: ghost
    component: {{ .Values.component }}

spec:
  selector:
    app: ghost
    component: {{ .Values.component }}

  ports:
    - name: {{ .Values.name }}
      port: {{ .Values.port }}
      protocol: {{ .Values.protocol }}
      targetPort: {{ .Values.targetPort }}
